Google = {
    'Afrikaans':'af',
    'Akan':'ak',
    'Amharic':'am',
    'Arabic':'ar',
    'Assamese':'as',
    'Aymara':'ay',
    'Azerbaijani':'az',
    'Belarusian':'be',
    'Bulgarian':'bg',
    'Bhojpuri':'bho',
    'Bambara':'bm',
    'Bengali':'bn',
    'Bosnian':'bs',
    'Catalan, Valencian':'ca',
    'Cebuano':'ceb',
    'Central Kurdish':'ckb',
    'Corsican':'co',
    'Czech':'cs',
    'Welsh':'cy',
    'Danish':'da',
    'German':'de',
    'Dogri':'doi',
    'Divehi, Dhivehi, Maldivian':'dv',
    'Ewe':'ee',
    'Greek, Modern (1453–)':'el',
    'English':'en',
    'United States':'en-US',
    'Esperanto':'eo',
    'Spanish, Castilian':'es',
    'Estonian':'et',
    'Basque':'eu',
    'Persian':'fa',
    'Finnish':'fi',
    'French':'fr',
    'Western Frisian':'fy',
    'Irish':'ga',
    'Gaelic, Scottish Gaelic':'gd',
    'Galician':'gl',
    'Guarani':'gn',
    'Konkani':'gom',
    'Gujarati':'gu',
    'Hausa':'ha',
    'Hawaiian':'haw',
    'Hindi':'hi',
    'Hmong':'hmn',
    'Croatian':'hr',
    'Haitian, Haitian Creole':'ht',
    'Hungarian':'hu',
    'Armenian':'hy',
    'Indonesian':'id',
    'Igbo':'ig',
    'Iloko':'ilo',
    'Icelandic':'is',
    'Italian':'it',
    'Hebrew':'iw',
    'Japanese':'ja',
    'Javanese':'jw',
    'Georgian':'ka',
    'Kazakh':'kk',
    'Central Khmer':'km',
    'Kannada':'kn',
    'Korean':'ko',
    'Kri':'kri',
    'Kurdish':'ku',
    'Kirghiz, Kyrgyz':'ky',
    'Latin':'la',
    'Luxembourgish, Letzeburgesch':'lb',
    'Ganda':'lg',
    'Lingala':'ln',
    'Lao':'lo',
    'Lithuanian':'lt',
    'Lushai':'lus',
    'Latvian':'lv',
    'Maithili':'mai',
    'Malagasy':'mg',
    'Maori':'mi',
    'Macedonian':'mk',
    'Malayalam':'ml',
    'Mongolian':'mn',
    'Manipuri, Meitei':'mni-Mtei',
    'Marathi':'mr',
    'Malay':'ms',
    'Maltese':'mt',
    'Burmese':'my',
    'Nepali':'ne',
    'Dutch, Flemish':'nl',
    'Norwegian':'no',
    'Sohto-Northern':'nso',
    'Chichewa, Chewa, Nyanja':'ny',
    'Oromo':'om',
    'Oriya':'or',
    'Punjabi, Panjabi':'pa',
    'Polish':'pl',
    'Pashto, Pushto':'ps',
    'Portuguese':'pt',
    'Quechua':'qu',
    'Romanian, Moldavian, Moldovan':'ro',
    'Russian':'ru',
    'Kinyarwanda':'rw',
    'Sanskrit':'sa',
    'Sindhi':'sd',
    'Sinhala, Sinhalese':'si',
    'Slovak':'sk',
    'Slovenian':'sl',
    'Samoan':'sm',
    'Shona':'sn',
    'Somali':'so',
    'Albanian':'sq',
    'Serbian':'sr',
    'Southern Sotho':'st',
    'Sundanese':'su',
    'Swedish':'sv',
    'Swahili':'sw',
    'Tamil':'ta',
    'Telugu':'te',
    'Tajik':'tg',
    'Thai':'th',
    'Tigrinya':'ti',
    'Turkmen':'tk',
    'Tagalog':'tl',
    'Turkish':'tr',
    'Tsonga':'ts',
    'Tatar':'tt',
    'Uighur, Uyghur':'ug',
    'Ukrainian':'uk',
    'Urdu':'ur',
    'Uzbek':'uz',
    'Vietnamese':'vi',
    'Xhosa':'xh',
    'Yiddish':'yi',
    'Yoruba':'yo',
    'Chinese Simplified':'zh-CN',
    'Chinese Traditional':'zh-TW',
    'Zulu':'zu',
}